### This code is from a freely accessible blog post on April 10 2023: 
###   https://blog.ephorie.de/building-and-backtesting-a-volatility-based-trading-strategy-with-chatgpt
###   License for original code not listed, code generated by ChatGPT; treating license as MIT.
###

# Step 1: Load necessary libraries and data
library(quantmod)
library(PerformanceAnalytics)

start_date <- as.Date("2000-01-01")
end_date <- as.Date("2021-12-31")
symbol <- "^GSPC"  # S&P 500 symbol

getSymbols(symbol, src = "yahoo", from = start_date, to = end_date, auto.assign = FALSE) -> sp500_data
price_data <- Ad(sp500_data)

# Step 2: Calculate volatility as a risk indicator
lookback_period <- 20
volatility <- runSD(ROC(price_data, n = 1, type = "discrete"), n = lookback_period) * sqrt(252)

# Step 3: Develop the trading strategy
threshold <- 0.15
signal <- ifelse(volatility < threshold, 1, 0)
signal <- lag(signal, 1)  # To avoid look-ahead bias
signal[is.na(signal)] <- 0

# Step 4: Backtest the strategy
returns <- ROC(price_data, n = 1, type = "discrete") * signal
strategy_returns <- na.omit(returns)

# Calculate benchmark returns
benchmark_returns <- ROC(price_data, n = 1, type = "discrete")
benchmark_returns <- na.omit(benchmark_returns)

# Step 5: Evaluate performance and risk metrics
comparison <- cbind(strategy_returns, benchmark_returns)
colnames(comparison) <- c("Strategy", "Benchmark")

charts.PerformanceSummary(comparison, main = "Long/Flat Strategy vs S&P 500 Benchmark")
